version: '3.3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: projectmunka
      MYSQL_DATABASE: projectmunka
    ports:
      - "3306:3306"

  api:
    build:
        dockerfile: Dockerfile.api
        context: .
    ports:
      - "3333:3333"

  client:
    build:
        dockerfile: Dockerfile.client
        context: .
    ports:
      - "80:80"
