version: '3.8'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: projectmunka
      MYSQL_DATABASE: projectmunka
  api:
    build:
        dockerfile: Dockerfile.api
    ports:
      - "3333:3333"
